name: 'testswadeploy'

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Build_docs
    runs-on: windows-latest
    environment: Production
    steps:
      - uses: actions/checkout@v4
      - name: Build doc
        shell: pwsh
        run: .\devops\doc\build.ps1
      - uses: actions/upload-artifact@v4
        with:
          name: doc-build
          path: deployment\doc
          retention-days: 5

  deploy:
    name: Deploy_docs
    needs: build
    runs-on: windows-latest
    environment: Production
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
     - uses: actions/checkout@v4
       with:
         sparse-checkout: |
           devops
     - uses: actions/download-artifact@v4
       with:
         name: doc-build
         path: ${{ github.workspace }}/doc
     - name: Azure login
       uses: azure/login@v1
       with:
         client-id: ${{  secrets.AZURE_CLIENT_ID  }}
         tenant-id: ${{  secrets.AZURE_TENANT_ID  }}         
         subscription-id: ${{  secrets.AZURE_SUB_ID  }}
     - name: Deploy doc
       shell: pwsh
       run: .\devops\doc\deploy.ps1
     - name: Deploy frontend
       id: build-deploy
       uses: Azure/static-web-apps-deploy@v1
       with:
           azure_static_web_apps_api_token: ${{ env.SWATOKEN }}
           action: "upload"
           skip_app_build: true
           skip_api_build: true
           app_location: doc
